[phases.setup]
nixPkgs = ['python39']

[phases.install]
cmds = [
    'pip install -r requirements.txt'
]

[phases.build]
cmds = [
    'python manage.py collectstatic --noinput',
    'python manage.py migrate --noinput'
]

[start]
cmd = 'gunicorn fc_backend.wsgi:application --bind 0.0.0.0:$PORT'
