services:
  - type: web
    name: fc-backend
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn fc_backend.wsgi:application --bind 0.0.0.0:$PORT"
    plan: free
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: "4"
    autoDeploy: false

databases:
  - name: fc-backend-db
    plan: free
