# Generated by Django 5.1 on 2025-02-13 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_deposit_deposit_type_transactionhistory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cryptocurrency', models.CharField(choices=[('USDT', 'USDT'), ('BTC', 'Bitcoin'), ('BCH', 'Bitcoin Cash'), ('ETH', 'Ethereum'), ('BNB', 'Binance Coin'), ('MATIC', 'Polygon'), ('SOL', 'Solana')], max_length=20)),
                ('network', models.CharField(choices=[('TRC20', 'TRON (TRC-20)'), ('ERC20', 'Ethereum (ERC-20)'), ('BEP20', 'BNB Smart Chain (BEP-20)'), ('BITCOIN', 'Bitcoin Network'), ('BCH', 'Bitcoin Cash Network'), ('POLYGON', 'Polygon Network'), ('SOLANA', 'Solana Network')], max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='wallet_qr_codes/')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Under Maintenance')], default='active', max_length=20)),
                ('memo', models.CharField(blank=True, help_text='For cryptocurrencies that require memo/tag', max_length=100, null=True)),
                ('description', models.TextField(blank=True, help_text='Additional information or instructions')),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Wallet Address',
                'verbose_name_plural': 'Wallet Addresses',
                'ordering': ['cryptocurrency', 'network'],
                'unique_together': {('cryptocurrency', 'network')},
            },
        ),
    ]
