# Generated by Django 5.1 on 2025-02-13 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_walletaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pin_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='pin_otp_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
