# Generated by Django 5.1 on 2025-02-14 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_profile_reset_password_expire_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='reset_password_expire',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='reset_password_token',
        ),
    ]
